### ISSUE TITLE
Oauth instead of JWT

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/target-dev.en#1]
Issue in ./help/dev/before-administer/configure-authentication.md
Apparently we are supposed to be using oauth and not jwt tokens now. So, this doc needs to be updated.

**Comment by mtalbot29** [comment]
@alisonasanchez, thanks for the heads-up. I added a note at the top of the article pointing to instructions on how to migrate to oauth.  I will now look at the existing article to see what updates are needed.

https://experienceleague.adobe.com/docs/target-dev/developer/api/configure-authentication.html?lang=en
