### ISSUE TITLE
Update the Caveats section of the Bulk Profile Update API documentation

### ISSUE THREAD

**Issue by MattAdobe** [AdobeDocs/target-dev.en#10]
Issue in ./help/dev/before-implement/methods-to-get-data-into-target/bulk-profile-update-api.md

Just like the "Caveats" section in the "Single profile update API" documentation, the "Caveats" section in the "Bulk profile update API" needs to include the following:

"Updates generally occur in under 1 hour, but may take as long as 24 hours to be reflected."

**Comment by mtalbot29** [comment]
Added new caveat: Updates generally occur in under one hour, but may take as long as 24 hours to be reflected.

https://experienceleague.adobe.com/docs/target-dev/developer/implementation/methods/bulk-profile-update-api.html

Thanks for the heads-up, Matt.

**Comment by mtalbot29** [comment]
Include the second paragraph as well?

Updates generally occur in under one hour, but might take as long as 24 hours to be reflected.

If you must send more updates, or require updates to be processed in shorter time frames, consider sending transactional profile updates via client-side update (preferred), or via the Adobe Target server-side [Delivery API](https://experienceleague.adobe.com/docs/target-dev/developer/api/delivery-api/overview.html?lang=en).

**Comment by MattAdobe** [comment]
I'm not sure about that paragraph, actually. I'll talk to Target Engineering about that. For now let's just get the statement noted in the issue added (re-added?). If the other paragraph is needed then I'll open a new issue/ticket for that.

**Comment by mtalbot29** [comment]
I will do it now. Thanks.

**Comment by mtalbot29** [comment]
Thanks for the addition. It is live:
https://experienceleague.adobe.com/docs/target-dev/developer/api/profile-apis/profile-bulk-api.html

**Comment by MattAdobe** [comment]
Hmm... if the ?lang=en parameter is appended to the URL then the change doesn't show. Can you correct that?

**Comment by mtalbot29** [comment]
Probably a cache issue. Try refreshing or incognito.

**Comment by MattAdobe** [comment]
Yep, you're right. I opened in a new browser and it's fine. Thank you!
