### ISSUE TITLE
Inconsistent explanation of how Bulk Profile Update API works

### ISSUE THREAD

**Issue by alexbishop010** [AdobeDocs/target-dev.en#11]
Issue in ./help/dev/before-implement/methods-to-get-data-into-target/bulk-profile-update-api.md

This doc explains that "The Bulk Profile Update API updates existing Target profiles only". This was true for v1 but not for v2 of the API. As per the Batch File section of this doc https://developers.adobetarget.com/api/#updating-profiles:

"If you are using Bulk Profile Update API v2, you need not specify all parameter values for each pcId. **Profiles are created for any pcId or mbox3rdPartyId that is not found in Target**. If you are using v1, profiles are not created for missing pcIds or mbox3rdPartyIds"

**Comment by mtalbot29** [comment]
Thanks for your input, Alex. I have updated the doc accordingly.
https://experienceleague.adobe.com/docs/target-dev/developer/implementation/methods/bulk-profile-update-api.html?lang=en
