### ISSUE TITLE
Correct the Postman link in delivery API Getting Started

### ISSUE THREAD

**Issue by roman-lemko** [AdobeDocs/target-dev.en#12]
The Postman Collection link on the [Delivery API Getting Started page](https://github.com/AdobeDocs/target-dev.en/blob/main/help/dev/before-implement/delivery-api-overview/getting-started.md) leads to a button svg:

> Postman is an application that makes it easy to fire API calls. [This Postman collection](https://run.pstmn.io/button.svg) contains sample Delivery API calls.

<img width="129" alt="image" src="https://github.com/AdobeDocs/target-dev.en/assets/22688697/b70511be-b3b9-4411-a326-bd4bd3bc9555">

**Comment by jkunz** [comment]
I just came across this too and came here to report it.

**Comment by mtalbot29** [comment]
Unfortunately, the Postman Collection is out-of-date so the link has been removed. I opened a dialog with Product Management to provide access to an updated collection.

Thanks for your feedback.
