### ISSUE TITLE
Content Typo

### ISSUE THREAD

**Issue by kierawilson25** [AdobeDocs/target-dev.en#19]
Issue in ./help/dev/implement/mobile/target-mobile-preview.md

under the 3rd section it says:
"Thw URL scheme"
Im assuming it should say "The URL scheme"

**Comment by mtalbot29** [comment]
Fixed. Thanks for the correction.
https://experienceleague.adobe.com/docs/target-dev/developer/mobile-apps/target-mobile-preview.html
