### ISSUE TITLE
link to Target Delivery API Postman Collection broken

### ISSUE THREAD

**Issue by StrawberryBe** [AdobeDocs/target-dev.en#2]
Issue in ./help/dev/before-administer/target-api-overview.md

Hi Team, the link to "Target Delivery API Postman Collection" is broken

**Comment by mtalbot29** [comment]
Link should be fixed.
https://experienceleague.adobe.com/docs/target-dev/developer/api/target-api-overview.html
Thanks for pointing this out to me.
