### ISSUE TITLE
We should also talk about Edge Network Server API for Target here  

### ISSUE THREAD

**Issue by manishadb** [AdobeDocs/target-dev.en#20]
Clients are getting misguided with the documentation and using the legacy Target server side SDKs for target server side implementation using this documentation and missing the Edge Network Server API even if they are using webSDK Client Side 

We should update this documentation so that they get clear guidance that 

- if they are using AT.JS and app measurement in client side than delivery API and Adobe Target Server Side SDKs should be used
- If they are using WebSDK in client side than Edge Network Server API for Target should be used 

Issue in ./help/dev/implement/server-side/server-side-overview.md

**Comment by mtalbot29** [comment]
Thanks for the information.
https://experienceleague.adobe.com/en/docs/target-dev/developer/server-side/server-side-overview
