### ISSUE TITLE
翻訳エラー: Target for mobile apps (日本語に切り替わらない)

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/target-dev.en#3]
Issue in ./help/dev/implement/mobile/overview.md

[現在の翻訳] 翻訳されていない (言語を「日本語」にしても、原文のまま)
[正しい翻訳] 翻訳されること
[原文] Target for mobile apps (タイトル以下全部)

**Comment by mtalbot29** [comment]
This page has now been localized. Please reopen issue if I misunderstood the issue.

Thank you for your input.
