### ISSUE TITLE
翻訳エラー: Target mobile preview (日本語にならない)

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/target-dev.en#4]
Issue in ./help/dev/implement/mobile/target-mobile-preview.md

[現在の翻訳] 翻訳されていません (原文で表示されています)
[正しい翻訳] 翻訳されること
[原文] Target mobile preview (このページ全部)

**Comment by mtalbot29** [comment]
This page has now been localized. Please reopen issue if I misunderstood the issue.

Thank you for your input.
