### ISSUE TITLE
Changes to the preview 

### ISSUE THREAD

**Issue by SydneeChristensen** [AdobeDocs/target-dev.en#6]
Issue in ./help/dev/implement/mobile/target-mobile-preview.md

- Remove the note at the top of the page

**Under prerequisites**
- Update the links for setting up the sdks to go here - https://developer.adobe.com/client-sdks/documentation/current-sdk-versions
- Delete all the content under 2 and replace it with either a link here - https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/ and explain that they need to scroll down to the visual preview section
or copy what is in that documentation and put this "For more information about setting URL schemes for iOS, see [Defining a Custom URL Scheme for Your App](https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app). For more information about setting URL schemes for Android, see [Create Deep Links to App Content](https://developer.android.com/training/app-links/deep-linking)."
- Delete all the content under 3 and change the name to "Set up collectLaunchInfo API for ios" and then link here - https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/ and explain that they need to scroll down to the visual preview section

Everything else can stay :)

**Comment by mtalbot29** [comment]
Looks like I did this and did not close. Thanks, Sydnee.
