### ISSUE TITLE
Links to outdated API Endpoint page

### ISSUE THREAD

**Issue by saucier-adobe** [AdobeDocs/target-dev.en#9]
Issue in ./help/dev/before-implement/methods-to-get-data-into-target/bulk-profile-update-api.md

Per Bennet Roy Joseph, Bulk Profile Update API links on this page are linked to outdated documentation. Please remove the links and include updated Profile Update API (single and batch) documentation on the page instead of links to Admin APIs.

**Comment by mtalbot29** [comment]
Moved legacy API documentation to the Target Developer Guide: https://experienceleague.adobe.com/docs/target-dev/developer/api/profile-apis/profile-api-overview.html

Thanks.
